### ISSUE TITLE
Module Crashes on load

### ISSUE THREAD

**Issue by neilpercy** [bitfocus/companion-module-panasonic-cameras#1]
Thanks for creating the new module, looking forward to trying out the new and improved features!

First time I’ve tried installing a module but I think I’ve done things correctly as it shows up in Companion and I can ‘Add’ it - but it immediately crashed, see below:
![IMG_0004](https://github.com/bitfocus/companion-module-panasonic-cameras/assets/76440481/57ea591a-b735-4db1-a13c-f1d7549963eb)

I’ve searched the companion user group and found reference to using ‘Yarn’ to make sure all dependencies are added(?) but I don’t have Yarn (or npm) installed?

It’s an up to date Companion Pi image running Companion 3.4.0(+7061) Beta, I tried 3.3.1 stable first. Raspberry Pi 8GB, VERSION="11 (bullseye)"

(I did look into installing Yarn, but there was mention of updating Node.js so I stopped here because I was getting a bit out of my comfort zone!)

Thanks for any info,
Neil

**Comment by premultiply** [comment]
Hi,
thank you for the feedback.

This should be more or less normal in dev mode as the (other) node.js dependencies used by this companion module are missing in the modules folder if you just download from this repository.
To include and run the module in dev mode you first need to install a complete environment including node.js 18 and a package manager like `npm` or `yarn`. Then run `npm install` in the module folder. This should install all required dependencies and fix the crash on load.

I'm just waiting for this module to be included in the official companion builds as that would make the whole thing easy as usual. All other dependencies are then included.
Then the module only needs to be activated from the companion user interface.

/ping @Julusian

**Comment by neilpercy** [comment]
Thanks for the info @premultiply, I think I’ve misunderstood how the process works.

Followed your instructions and the module is working fine now! 

Many thanks, a day of exploring new feedbacks and functions ahead….   Much appreciated
