### ISSUE TITLE
Module crashes when connecting to UB300

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion-module-panasonic-cameras#10]
Hi,
I have tested with the new UB300 changes this morning, and we get module crashes. It still connects to other camera types ok.

From the logs:

> system: ** Connection started **
> Starting up module class: PanasonicCameraInstance
> Sentry disabled
> Module-host accepted registration
> info: Cam request: http://172.20.142.191:80/cgi-bin/aw_cam?cmd=QID&res=1
> info: Cam response: OID:AK-UB300
> info: Detected Camera Model: AK-UB300
> error: Cam request http://172.20.142.191:80/cgi-bin/aw_cam?cmd=QID&res=1 failed: TypeError: Cannot read properties of undefined (reading 'find')
> info: Web request: http://172.20.142.191:80/cgi-bin/getinfo?FILE=1
> info: Web request: http://172.20.142.191:80/cgi-bin/get_basic
> info: camdata request: http://172.20.142.191:80/live/camdata.html
> debug: Trying to listen to TCP from camera
> info: Listening for camera updates on localhost:31015
> debug: TCP subscription request: http://172.20.142.191:80/cgi-bin/event?connect=start&my_port=31015&uid=0
> error: webpack://panasonic-cameras/./src/presets.js?:1419
> 						option: SERIES.capabilities.whiteBalance.dropdown[0].id,
> 						                                                 ^
> 
> TypeError: Cannot read properties of undefined (reading '0')
>     at getPresetDefinitions (webpack://panasonic-cameras/./src/presets.js?:1419:56)
>     at PanasonicCameraInstance.init_presets (webpack://panasonic-cameras/./src/index.js?:522:94)
>     at PanasonicCameraInstance.reInitAll (webpack://panasonic-cameras/./src/index.js?:506:8)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
> Node.js v18.20.2
> Starting up module class: PanasonicCameraInstance
> Sentry disabled
> error: Module registration failed Error: Call timed out
>     at IpcWrapper.sendWithCb (webpack://panasonic-cameras/./node_modules/@companion-module/base/dist/host-api/ipc-wrapper.js?:39:30)
>     at eval (webpack://panasonic-cameras/./node_modules/@companion-module/base/dist/entrypoint.js?:114:20)
> Starting up module class: PanasonicCameraInstance
> Sentry disabled
> error: Module registration failed Error: Call timed out
>     at IpcWrapper.sendWithCb (webpack://panasonic-cameras/./node_modules/@companion-module/base/dist/host-api/ipc-wrapper.js?:39:30)
>     at eval (webpack://panasonic-cameras/./node_modules/@companion-module/base/dist/entrypoint.js?:114:20)
> system: ** Connection stopped **

**Comment by premultiply** [comment]
@phillipivan Does it work correctly now?

**Comment by phillipivan** [comment]
Hi, I'll run up the current build this morning (in a few hours) and confirm where it's at.

**Comment by phillipivan** [comment]
My colleague did some further testing and updated the other [ticket](https://github.com/bitfocus/companion-module-panasonic-cameras/issues/4#issuecomment-2339309522).
