### ISSUE TITLE
AW HE 130 & AW HE 42  Cam data

### ISSUE THREAD

**Issue by phillipivan** [bitfocus/companion-module-panasonic-cameras#11]
Please see attached cam data from AW HE 130 & AW HE 42 model. Just posting in case its useful, as I can see the Camera_Dumps folder is missing these models we have.
[he130_camdata.zip](https://github.com/user-attachments/files/16901137/he130_camdata.zip)
[he42_camdata.zip](https://github.com/user-attachments/files/16901142/he42_camdata.zip)

**Comment by premultiply** [comment]
Thanks!

Fixed by https://github.com/bitfocus/companion-module-panasonic-cameras/commit/5c022eeab19cded61ef34c9bdd1fa1042f95d709
