### ISSUE TITLE
Reboot camera

### ISSUE THREAD

**Issue by TRT-777** [bitfocus/companion-module-panasonic-cameras#12]
Hi! You can add a feature that allows you to reboot the camera?

**Comment by premultiply** [comment]
I'm still not sure how this works exactly.

Can you provide a working HTTP request flow?

**Comment by TRT-777** [comment]
Thanks, I found it, but it only worked with basic authorization, I don’t know if it’s possible with digest?

**Comment by premultiply** [comment]
Should be as easy as GET http://admin:12345@192.168.0.10/cgi-bin/initial?cmd=reset&Randomnum=12345

I nerver tried it before :)
