### ISSUE TITLE
Connection stability/issues with AW-HN40 camera

### ISSUE THREAD

**Issue by cpuguru07** [bitfocus/companion-module-panasonic-cameras#2]
Camera connection is unstable & variables do not update with Subscription enabled. Disabling Subscription seems to result in a more stable connection, but lots of errors in the Log (with debug enabled OR disabled). See attached logs.
[S7-39CH724193HH_companion_log_20240724-1127.csv](https://github.com/user-attachments/files/16364293/S7-39CH724193HH_companion_log_20240724-1127.csv)
Feedbacks for currently selected presets does not appear to work.

I am very hesitant to take the time to migrate to this module (over the legacy PTZ module) with these bugs.

**Comment by premultiply** [comment]
It looks like there are several things mixed up.

Lets see how we can solve it step by step.

Are the cameras located in the local network or is this some kind of remote connection with a NAT router or firewall in between?

- First try to disable all camera instances and wait for some seconds.
- Then reactivate only one instance. Set it manually to your base camera type "HE40".
I was not shure how they respond to OID command.
The module may no know about variant HN40 yet and it is even not important for control.


If you use a remote connection, router, firewall, etc. the subscription mode will not work at all as the camera event connection has no chance to be established. It is clear that there will be no feedbacks etc. in this case if you do no disable the subscription manually.
This is how the the protocol works.

The only way is to poll the data from the camera. This should be possible if subscription is disabled and HE40 is selected manually.

If the module still claims about timeouts or reconnection your connection seems to have a large round trip time (delay).
Try to increase the timeout and/or the poll delay until it allows for a stable operation.

Please disable and reenable the module after all those basic module adjustments to apply the changed setting properly and let all async commands timeout properly.

**Comment by cpuguru07** [comment]
It is on the local network (same subnet and VLAN, no remote connection, NAT, or firewall in between). I think the issue with the module timing out was with the Subscription setting. It is much more stable (usable) with the Subscription setting disabled. The buttons and feedbacks seem to work much more consistently.
Logs still show many errors (attached) - many failures retrieving preset thumbnails (response 404 not found).
Module seems to save/recall/clear presets successfully. Will continue testing.

[S7-39CH724193HH_companion_log_20240724-1419.csv](https://github.com/user-attachments/files/16366110/S7-39CH724193HH_companion_log_20240724-1419.csv)

**Comment by premultiply** [comment]
> I think the issue with the module timing out was with the Subscription setting. It is much more stable (usable) with the Subscription setting disabled.

Subscription should be **much** more responsive. This is the normal operation mode used by the Panasonic RP PTZ control panels.

Please try again. It **should** work.

> Logs still show many errors (attached) - many failures retrieving preset thumbnails (response 404 not found).

Ah, simple thing: The HE40 just has no preset thumbnails ;)

Maybe I should filter the requests on camera series without thumbnails?


By the way having debug log enabled with poll mode will place a huge load on the companion system with fast growing log files due to the heavy and continuous communication with each camera.
