### ISSUE TITLE
Iris value as a variable

### ISSUE THREAD

**Issue by AlexHasker** [bitfocus/companion-module-panasonic-cameras#3]
It would be ace if the Exposure - Iris > Set > Iris Setting value could be entered as a variable. Reason behind this would be so that we could make a trigger that takes the currrent Auto Iris value and make it the current Manual Iris value when switching from Auto to Manual to avoid exposure jumps.

From my undertsanding, currently the Exposure - Iris > Set > Iris Setting value can only be entered as a number, I believe that there needs to be a $ GLOBE symbol next to the value box to allow variables to be entered.

PS - Thanks for the new Panasonic Camera module , so good  !!

**Comment by premultiply** [comment]
I have to check that in detail.

Sometimes the position read value type/range is not equal to the set value.

But maybe it is easy to.

**Comment by premultiply** [comment]
A number input field is used here, in which Companion does not support variables.
https://bitfocus.github.io/companion-module-base/interfaces/CompanionInputFieldNumber.html

I'm sorry, I can't change that at the moment with reasonable effort.

**Comment by premultiply** [comment]
Fixed by #19
