### ISSUE TITLE
Request - Integrate Iris, AWB & ABB functions with AK-UB300 model

### ISSUE THREAD

**Issue by JuddiP** [bitfocus/companion-module-panasonic-cameras#4]
First off, thank you for this updated module. We have been using it to control a range of models both locally on our network, and remote when take kits to regional towns for live broadcasting.

I would like to request, if possible, implementation of the following functions with the AK-UB300 camera model:

1. Iris (actions, feedbacks, variables, presets)
2. White balance (actions, feedbacks, variables, presets)
3. Auto black balance (action, feedback)
 
I am happy to perform any testing outside of our production schedule.

As a reference, we are hoping to add a Loupdeck Live surface to each control room as a supplement to the ROPs that are already installed. This module will provide less intimidating shading of our cameras for our more inexperienced operators.

**Comment by premultiply** [comment]
Can you please provide the commands for the settings you are requesting?

**Comment by JuddiP** [comment]
Hi @premultiply,

I'm just taking a look at the [documentation now](https://eww.pass.panasonic.co.jp/pro-av/support/content/guide/DEF/HE50_120_IP/HDIntegratedCamera_InterfaceSpecifications-E.pdf). It seems there are different types of iris controls, and a lot of the functions available with the all-in-one PTZ units are not available with the AK-UB300. I've collated what I think will work - please let me know if you would prefer these references in a different format (text, page number):

## **IRIS**
![image](https://github.com/user-attachments/assets/be8ee1fc-28dd-4e0b-a5fd-82ff5b745912)
![image](https://github.com/user-attachments/assets/2175af88-a065-4ce0-8472-7b86203306c5)
![image](https://github.com/user-attachments/assets/f5d6f46f-d045-47f9-9421-739f8c48da7f)

## **ZOOM**
![image](https://github.com/user-attachments/assets/6a4cce28-867c-414e-b7b8-c17ce5783141)

## **LENS INFO**
![image](https://github.com/user-attachments/assets/58858381-8e46-42b4-a555-a76095b8e724)

## **AWB**
![image](https://github.com/user-attachments/assets/4d39bbd9-5e7b-4111-bfef-5d3cf259b1df)

## **ABB**
![image](https://github.com/user-attachments/assets/5401fc1b-3a57-4821-b16e-2740fecb911b)

**Comment by premultiply** [comment]
Can you please add the raw file from `http://CAM-IP/live/camdata.html` of any UB300 camera?

UB300 is very different to all other cams.

**Comment by JuddiP** [comment]
Sorry it's not been straight forward! I appreciate you spending some time on this.

Here is the raw file data:

`CGI_TIME:70 TITLE:LA-CAM-1 OID:AK-UB300 OUS:0 OER:0 OSA:87:0x05 OBR:0 TLR:0 TLG:0 OSI:18:0xFFF:0x555:0xD24 ORS:0 ORV:0x2F5 OSD:48:0x32 OSI:1D:0x32 OIF:0x19 OFT:0 OSF:1 OSG:59:0 OSG:5A:0 OSG:5D:0x04 OSA:65:0x00 OGS:0x01 OSA:50:0x7C OSA:51:0x7F OSA:52:0x82 OSA:60:0 OSG:39:0x8BE OSG:3A:0x811 OSG:4A:0x77 OSG:4C:0x800 OSG:4E:0x800 OSG:A0:0 OSA:84:0 OSA:00:0 OSG:A5:N:0x1F OSG:A5:P:0x1F OSG:A6:N:0x1F OSG:A6:P:0x1F OSG:A7:N:0x1F OSG:A7:P:0x1F OSG:A8:N:0x1F OSG:A8:P:0x1F OSG:A9:N:0x1F OSG:A9:P:0x1F OSG:AA:N:0x1F OSG:AA:P:0x1F OSA:85:0 OSG:A4:0 OSD:86:0x80 OSD:87:0x80 OSD:88:0x80 OSD:89:0x80 OSD:8A:0x80 OSD:8B:0x80 OSD:8C:0x80 OSD:8D:0x80 OSD:8E:0x80 OSD:8F:0x80 OSD:90:0x80 OSD:91:0x80 OSD:92:0x80 OSD:93:0x80 OSD:94:0x80 OSD:95:0x80 OSD:96:0x80 OSD:97:0x80 OSD:80:0x80 OSD:81:0x80 OSD:82:0x80 OSD:83:0x80 OSD:84:0x80 OSD:85:0x80 OSG:B0:0 OSG:B1:0 OSG:B2:0x80 OSG:B3:0x80 OSG:93:0 OSD:B0:0x80 OSI:20:0x00F3C:0x0 ODT:1 OSA:30:80 OSA:31:0x0F OSG:32:0x1B OSG:30:0x12 OSG:35:0x12 OSD:22:0x00 OSA:38:0x80 OSA:39:0x80 OSG:40:0x00 OSG:41:0x00 OSA:3B:0 OSG:3F:0x05 OSG:3E:0 OSD:26:0x08 OSA:40:0 OSA:41:0 OSG:42:0 OSG:44:0x0C8 OSG:45:0x0C8 OSA:49:0 OSG:47:6 OSG:48:6 OSG:49:0xBF OSA:45:0x12 OSA:46:0x08 OSA:47:0x2B OSG:4F:0x05A OSD:3A:01 OSG:B5:3 OSG:B6:0 OSG:B7:1 OSG:CA:0 OSG:CB:0x8 OSG:CC:0x80 OSI:32:0 OSI:33:1 OSI:16:1 OSI:17:1 OSI:1A:7 OSI:1B:0x800 OSI:1C:0x800 OSE:7B:0x11 OSA:88:0 OSI:2C:0 OSI:2D:0x00 OSI:2E:1 OSI:2F:1 OSA:0D:0 OSI:30:0 OSI:31:1 OSA:11:1 OSG:96:0x80 OSD:35:0x00 OSD:36:0x00 OSD:37:0x00 OSA:0A:1 OSG:86:0 OSI:34:0x1194 OSI:35:0x80 OSI:36:0x80 OSA:0F:0x00 OSA:10:3 OSA:21:0x62 OSA:25:0x7C OSA:0B:0 OSA:07:0x80 OSA:08:0x80 OSA:09:0x80 OSA:2D:1 OSA:20:0x86 OSA:22:0x80 OSA:23:0x80 OSA:24:0x82 OSA:26:0x80 OSA:27:0x80 OSA:28:0x86 OSA:29:0x84 OSG:97:4 OSI:39:0 OSI:3A:0 OSI:3B:0 OSI:3C:0 OSI:3D:0x80 OSI:3E:0x80 OSI:3F:0x80 OSI:40:0 OSI:41:0x80 OLR:0 OLG:0 OSI:42:0x82 OSI:43:0x80 OSI:44:2 OSI:2A:1 ODE:0 ODK:01:0 ODK:02:0x3`

**Comment by premultiply** [comment]
Can you please save the `camdata.html` file to disk from browser and attach it as file? Thanks.

**Comment by JuddiP** [comment]
My apologies -- here you go:
[UB300-camdata.zip](https://github.com/user-attachments/files/16859224/UB300-camdata.zip)

**Comment by JuddiP** [comment]
Hi @premultiply,

I've tested the added iris actions, feedbacks and presets -- **they're working well.**

Thank you for implementing those!

I will test AWB & ABB once we are out of our production for this week.
